import { Link } from "react-router-dom";
import TopBar from "../components/TopBar.jsx";
import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";
import PageMeta from "../components/PageMeta.jsx";
import { TEAM_MEMBERS } from "../data/team.js";

const principles = [
  { number: "01", title: "Minh bạch thông tin", desc: "Mỗi nhu cầu kết nối được trình bày với mục tiêu, giai đoạn, nguồn lực cần thiết và đầu mối trao đổi rõ ràng." },
  { number: "02", title: "Kết nối có chọn lọc", desc: "Các bên gặp nhau dựa trên lĩnh vực quan tâm, năng lực bổ trợ và định hướng hợp tác phù hợp." },
  { number: "03", title: "Quyết định độc lập", desc: "Nhà đầu tư và đối tác tự thẩm định pháp lý, tài chính, vận hành trước khi đưa ra quyết định." },
];
const identity = [
  ["fa-compass", "Định vị thương hiệu", "Một nền tảng kết nối đáng tin cậy, nơi nguồn lực phù hợp gặp đúng nhu cầu phát triển."],
  ["fa-bullseye", "Sứ mệnh", "Kích hoạt những quan hệ hợp tác có giá trị bằng thông tin rõ ràng, cách làm có cấu trúc và tinh thần đồng hành."],
  ["fa-eye", "Tầm nhìn", "Trở thành hệ sinh thái được lựa chọn cho hành trình xây dựng doanh nghiệp và giá trị bền vững tại Việt Nam."],
];
const timeline = [["2022", "Khởi nguồn", "Hình thành định hướng kết nối năng lực chuyên môn và cơ hội phát triển."], ["2023", "Xây nền tảng", "Chuẩn hóa phương thức kết nối, hợp tác và hỗ trợ vận hành."], ["2024", "Mở rộng hệ sinh thái", "Phát triển các nhánh dịch vụ, kết nối kinh doanh và đầu tư."], ["Hôm nay", "Cộng hưởng giá trị", "Tiếp tục hoàn thiện Matrix Network, Connect, Ventures và Academy."]];
const values = [["Chính trực", "Thông tin trung thực, kỳ vọng rõ ràng và tôn trọng cam kết."], ["Hợp tác", "Chủ động tìm điểm bổ trợ và cùng chịu trách nhiệm trong phạm vi đã thống nhất."], ["Thực chất", "Ưu tiên nhu cầu thật, năng lực thật và kết quả có thể đánh giá."], ["Phát triển bền vững", "Cân bằng giá trị kinh tế với trách nhiệm đối với con người và cộng đồng."]];
const operatingModel = [["Network", "Kết nối năng lực dịch vụ và nguồn lực chuyên môn."], ["Connect", "Mở rộng cơ hội hợp tác giữa doanh nghiệp và đối tác."], ["Ventures", "Sàng lọc và kết nối cơ hội đầu tư, dự án."], ["Academy", "Phát triển năng lực lãnh đạo và chuyên môn."]];
const workflow = [["01", "Lắng nghe nhu cầu", "Làm rõ mục tiêu, vai trò và phạm vi trao đổi."], ["02", "Chuẩn hóa thông tin", "Tổ chức thông tin nền tảng và xác định phần cần kiểm chứng."], ["03", "Kết nối phù hợp", "Giới thiệu đầu mối khi năng lực và nhu cầu có điểm tương đồng."], ["04", "Cùng đánh giá", "Các bên tự thẩm định, thống nhất điều kiện và quyết định hợp tác."]];

export default function About() {
  return <>
    <PageMeta title="Giới thiệu | Matrix Holding" description="Matrix Holding xây dựng hệ sinh thái cộng đồng kết nối nhà đầu tư, chủ dự án và đối tác chuyên môn." />
    <TopBar /><Header />
    <main>
      <div className="title-band" style={{backgroundImage:"linear-gradient(90deg,#1f0d26ee,#592b50b8),url(/assets/matrix-community-team.jpg)"}}><h1>Về Matrix Holding</h1></div>
      <section className="section about-preview"><div className="container about-grid about-story">
        <figure className="about-photo about-team-photo"><img src="/assets/matrix-community-team.jpg" alt="Hình ảnh đại diện đội ngũ kết nối cộng đồng Matrix Holding"/><span>Con người kết nối<br/>Giá trị lan tỏa</span><figcaption>Hình ảnh đại diện cho đội ngũ kết nối Matrix Holding</figcaption></figure>
        <div className="about-copy"><p className="eyebrow">NƠI VỐN, DỰ ÁN VÀ CHUYÊN MÔN GẶP NHAU</p><h2>Biến một cuộc gặp đúng người thành <em>khởi đầu có giá trị.</em></h2><p>Trong đầu tư, cơ hội tốt thường không thiếu. Điều khó hơn là tìm được người phù hợp, hiểu đúng nhu cầu và có đủ thông tin để bắt đầu một cuộc trao đổi nghiêm túc.</p><p>Matrix Holding xây dựng một cộng đồng nơi nhà đầu tư tìm thấy dự án đáng quan tâm, chủ dự án tiếp cận nguồn lực phù hợp, còn chuyên gia đưa năng lực của mình vào những bài toán thực tế.</p><div className="about-points"><span><i className="fa-solid fa-circle-check"/> Nhu cầu được trình bày rõ</span><span><i className="fa-solid fa-circle-check"/> Kết nối theo mức độ phù hợp</span><span><i className="fa-solid fa-circle-check"/> Thẩm định trước quyết định</span></div><p className="detail-note"><i className="fa-solid fa-shield-halved"/> Matrix Holding hỗ trợ kết nối ban đầu, không cam kết lợi nhuận và không thay thế tư vấn pháp lý hoặc tài chính độc lập.</p><Link className="btn" to="/contact">Bắt đầu một kết nối <i className="fa-solid fa-arrow-right"/></Link></div>
      </div></section>
      <section className="section services-section"><div className="container"><div className="section-heading"><p className="eyebrow">BẢN SẮC MATRIX HOLDING</p><h2>Định hướng rõ ràng cho <em>một hành trình dài hạn.</em></h2></div><div className="about-identity-grid">{identity.map(([icon,title,desc]) => <article key={title}><i className={`fa-solid ${icon}`} /><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">GIÁ TRỊ CỐT LÕI</p><h2>Nguyên tắc định hình <em>cách chúng tôi hợp tác.</em></h2></div><div className="about-identity-grid">{values.map(([title,desc])=><article key={title}><i className="fa-solid fa-gem"/><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section services-section"><div className="container"><div className="section-heading"><p className="eyebrow">MÔ HÌNH HOẠT ĐỘNG</p><h2>Bốn nhánh năng lực trong <em>một hệ sinh thái.</em></h2><p>Các đơn vị phối hợp theo nhu cầu cụ thể, cùng hướng tới khả năng triển khai và giá trị dài hạn.</p></div><div className="about-identity-grid">{operatingModel.map(([title,desc])=><article key={title}><i className="fa-solid fa-circle-nodes"/><h3>Matrix {title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">QUY TRÌNH LÀM VIỆC</p><h2>Từ nhu cầu đến một cuộc trao đổi <em>có cơ sở.</em></h2></div><div className="timeline-list">{workflow.map(([number,title,desc])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">LỊCH SỬ HÌNH THÀNH</p><h2>Từng bước tạo dựng <em>nền tảng cộng hưởng.</em></h2></div><div className="timeline-list">{timeline.map(([year,title,desc]) => <article key={year}><span>{year}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section team-section"><div className="container"><div className="section-heading"><p className="eyebrow">ĐỘI NGŨ KẾT NỐI</p><h2>Ba đầu mối đồng hành cùng <em>cộng đồng.</em></h2><p>Các hồ sơ dưới đây đang dùng nội dung mẫu. Hãy thay bằng tên, ảnh và kinh nghiệm thật của nhân sự trước khi công bố website.</p></div><div className="team-grid">{TEAM_MEMBERS.map(member=><article className="team-card" key={member.name}><img src={member.image} style={{objectPosition:member.imagePosition}} alt={`Hình ảnh đại diện ${member.role}`}/><div><span>NỘI DUNG MẪU</span><h3>{member.name}</h3><strong>{member.role}</strong><p>{member.bio}</p></div></article>)}</div></div></section>
      <section className="section services-section"><div className="container"><div className="section-heading"><p className="eyebrow">CÁCH CHÚNG TÔI VẬN HÀNH</p><h2>Ba nguyên tắc cho một cộng đồng <em>đáng tin cậy.</em></h2></div><div className="sector-grid">{principles.map(item=><article className="sector-info" key={item.number}><span className="eyebrow">NGUYÊN TẮC {item.number}</span><h3>{item.title}</h3><p>{item.desc}</p></article>)}</div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">ĐỐI TÁC CHIẾN LƯỢC</p><h2>Cộng tác với những năng lực <em>bổ trợ cho nhau.</em></h2><p>Matrix Holding hướng tới hợp tác cùng doanh nghiệp, chuyên gia và tổ chức có năng lực trong các lĩnh vực:</p></div><div className="partner-tags"><span>Pháp lý & quản trị</span><span>Tài chính & kế toán</span><span>Công nghệ & dữ liệu</span><span>Thương hiệu & truyền thông</span><span>Vận hành & chuỗi cung ứng</span><span>Đào tạo & phát triển lãnh đạo</span></div><p className="form-note">Danh sách trên mô tả nhóm chuyên môn hợp tác, không phải danh sách đối tác đã ký kết.</p></div></section>
      <section className="leadership manifesto"><div className="container"><p className="eyebrow">TUYÊN NGÔN MATRIX HOLDING</p><blockquote>“Một hệ sinh thái có giá trị khi mỗi kết nối bắt đầu từ sự tin cậy, được xây trên năng lực thật và hướng đến kết quả bền vững.”</blockquote><p className="manifesto-credit">Định hướng thương hiệu Matrix Holding</p></div></section>
      <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">CAM KẾT & LỢI THẾ</p><h2>Rõ ràng trong vai trò, <em>kiên định với nguyên tắc.</em></h2></div><div className="about-identity-grid"><article><i className="fa-solid fa-shield-halved"/><h3>Cam kết minh bạch</h3><p>Không cam kết lợi nhuận, không nhận tiền đầu tư thay mặt nhà đầu tư và không thay thế dịch vụ tư vấn chuyên môn độc lập.</p></article><article><i className="fa-solid fa-diagram-project"/><h3>Kết nối đa năng lực</h3><p>Bốn nhánh hệ sinh thái hỗ trợ tiếp cận dịch vụ, đối tác, cơ hội đầu tư và đào tạo trong cùng một nền tảng.</p></article><article><i className="fa-solid fa-list-check"/><h3>Quy trình có cấu trúc</h3><p>Nhu cầu và phạm vi trao đổi được làm rõ để các bên chủ động đánh giá bước tiếp theo.</p></article></div></div></section>
      <section className="section"><div className="container section-heading section-heading-row"><div><p className="eyebrow">VAI TRÒ TRONG HỆ SINH THÁI</p><h2>Nhà đầu tư · Chủ dự án · Đối tác chuyên môn</h2><p>Mỗi vai trò mang một nguồn lực khác nhau. Giá trị hình thành khi nhu cầu, năng lực và trách nhiệm được trao đổi thẳng thắn.</p></div><Link className="btn" to="/contact">Tham gia cộng đồng</Link></div></section>
    </main><Footer />
  </>;
}
